spring.application.name=TFG_BE
server.port=8087

# ELEGIMOS PERFIL LOCAL EN POSTGRE o RAILWAY ONLINE
spring.profiles.active=local
# spring.profiles.active=railway
# spring.profiles.active=mysql


spring.jpa.generate-ddl=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# LOGGING

logging.level.org.springframework.web=DEBUG



# SECURITY

#spring.security.user.name=b
#spring.security.user.password=


#jwt.secret=
#jwt.expiration=

jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:}
gemini.api.key=${GEMINI_API_KEY:}