-- public.admins definition
-- Drop table
-- DROP TABLE admins;
CREATE TABLE admins ( id_admin int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, email varchar(255) NULL, "password" varchar(255) NULL, role_name varchar(255) NULL, username varchar(255) NULL, CONSTRAINT admins_pkey PRIMARY KEY (id_admin), CONSTRAINT uq_admins_email UNIQUE (email), CONSTRAINT uq_admins_username UNIQUE (username));

-- public.roles definition
-- Drop table
-- DROP TABLE roles;
CREATE TABLE roles ( id_role int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, role_name varchar(255) NULL, CONSTRAINT roles_pkey PRIMARY KEY (id_role));

-- public.shifts definition
-- Drop table
-- DROP TABLE shifts;
CREATE TABLE shifts ( id_shift int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, assign_shift varchar(255) NULL, id_restaurant bigserial NOT NULL, CONSTRAINT shifts_pkey PRIMARY KEY (id_shift));

-- public.users definition
-- Drop table
-- DROP TABLE users;
CREATE TABLE users ( id_user int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at date NULL, email varchar(255) NULL, first_name varchar(255) NULL, is_active bool NULL, last_name varchar(255) NULL, "password" varchar(255) NULL, updated_at date NULL, CONSTRAINT uq_users_email UNIQUE (email), CONSTRAINT users_pkey PRIMARY KEY (id_user));

-- public.restaurants definition
-- Drop table
-- DROP TABLE restaurants;
CREATE TABLE restaurants ( address varchar(255) NULL, capacity int4 NULL, country varchar(255) NULL, phone varchar(255) NULL, restaurant_name varchar(255) NOT NULL, total_tables int4 NULL, id_restaurant bigserial NOT NULL, cif varchar(9) NOT NULL, id_user int4 NULL, CONSTRAINT pk_restaurant PRIMARY KEY (id_restaurant), CONSTRAINT uq_restaurants_cif UNIQUE (cif), CONSTRAINT fk_restaurants_users FOREIGN KEY (id_user) REFERENCES users(id_user));

-- public.signup_requests definition
-- Drop table
-- DROP TABLE signup_requests;
CREATE TABLE signup_requests ( id_request serial4 NOT NULL, first_name varchar(100) NOT NULL, last_name varchar(150) NOT NULL, email varchar(255) NOT NULL, phone varchar(30) NULL, restaurant_name varchar(255) NULL, message text NULL, status varchar(20) DEFAULT 'PENDING' NOT NULL, created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, resolved_at timestamp NULL, resolved_by_admin_id int4 NULL, dni varchar(9) NULL, CONSTRAINT signup_requests_pkey PRIMARY KEY (id_request), CONSTRAINT fk_signup_request_admin FOREIGN KEY (resolved_by_admin_id) REFERENCES admins(id_admin) ON DELETE SET NULL);

-- public."tables" definition
-- Drop table
-- DROP TABLE "tables";
CREATE TABLE "tables" ( id_table int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, status varchar(255) NULL, table_capacity int4 NULL, table_number int4 NULL, id_restaurant bigserial NOT NULL, CONSTRAINT tables_pkey PRIMARY KEY (id_table), CONSTRAINT tables_status_check CHECK (((status)::text = ANY ((ARRAY['BOOKED'::character varying, 'NOT_BOOKED'::character varying, 'CONFIRMED'::character varying, 'PENDING'::character varying])::text[]))), CONSTRAINT uq_tables_restaurant_table_number UNIQUE (id_restaurant, table_number), CONSTRAINT fk_tables_restaurants FOREIGN KEY (id_restaurant) REFERENCES restaurants(id_restaurant));

-- public.employees definition
-- Drop table
-- DROP TABLE employees;
CREATE TABLE employees ( hire_date date NULL, hourly_wage float8 NULL, dni varchar(9) NOT NULL, id_role int4 NULL, id_user int4 NOT NULL, id_shift int4 NULL, id_restaurant bigserial NULL, CONSTRAINT employees_pkey PRIMARY KEY (id_user), CONSTRAINT uq_employees_dni UNIQUE (dni), CONSTRAINT fk_employees_restaurants FOREIGN KEY (id_restaurant) REFERENCES restaurants(id_restaurant), CONSTRAINT fk_employees_roles FOREIGN KEY (id_role) REFERENCES roles(id_role), CONSTRAINT fk_employees_shifts FOREIGN KEY (id_shift) REFERENCES shifts(id_shift), CONSTRAINT fk_employees_users FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE CASCADE);

-- public.table_assignment definition
-- Drop table
-- DROP TABLE table_assignment;
CREATE TABLE table_assignment ( id_assignment int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, end_time timestamp(6) NULL, start_time timestamp(6) NOT NULL, id_employee int4 NOT NULL, id_table int4 NOT NULL, CONSTRAINT table_assignment_pkey PRIMARY KEY (id_assignment), CONSTRAINT fk_table_assignment_employees FOREIGN KEY (id_employee) REFERENCES employees(id_user), CONSTRAINT fk_table_assignment_tables FOREIGN KEY (id_table) REFERENCES "tables"(id_table));


-- Secuencias
SELECT setval('restaurants_id_restaurant_seq', COALESCE((SELECT MAX(id_restaurant) FROM restaurants), 1), false);
/*AÑADIR EN LA BBDD A PARTIR DE AQUI*/

-- public.restaurant_elements definition
CREATE TABLE restaurant_elements (
    id_element int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type varchar(50) NOT NULL,
    pos_x int4 NOT NULL,
    pos_y int4 NOT NULL,
    width int4 NULL,
    height int4 NULL,
    rotation int4 DEFAULT 0,
    id_restaurant bigserial NOT NULL,
    CONSTRAINT elements_pkey PRIMARY KEY (id_element),
    CONSTRAINT fk_elements_restaurants FOREIGN KEY (id_restaurant) REFERENCES public.restaurants(id_restaurant) ON DELETE CASCADE
);

-- Plantas
CREATE TABLE floors (
    id_floor int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255) NOT NULL,
    id_restaurant int8 NOT NULL,
    CONSTRAINT floors_pkey PRIMARY KEY (id_floor),
    CONSTRAINT fk_floors_restaurants FOREIGN KEY (id_restaurant) REFERENCES restaurants(id_restaurant) ON DELETE CASCADE
);

-- Parches Multifloor
ALTER TABLE "tables" ADD COLUMN IF NOT EXISTS pos_x int4 DEFAULT 0;
ALTER TABLE "tables" ADD COLUMN IF NOT EXISTS pos_y int4 DEFAULT 0;
ALTER TABLE "tables" ADD COLUMN IF NOT EXISTS id_floor int4;
ALTER TABLE "tables" ADD CONSTRAINT fk_tables_floors FOREIGN KEY (id_floor) REFERENCES floors(id_floor) ON DELETE SET NULL;

ALTER TABLE restaurant_elements ADD COLUMN IF NOT EXISTS id_floor int4;
ALTER TABLE restaurant_elements ADD CONSTRAINT fk_elements_floors FOREIGN KEY (id_floor) REFERENCES floors(id_floor) ON DELETE SET NULL;


/*SI da error turnos
ALTER TABLE shifts DROP CONSTRAINT IF EXISTS uklws0m02gtraycujwdxuulvgyq;
ALTER TABLE shifts ADD CONSTRAINT uq_shifts_assign_shift_restaurant UNIQUE (assign_shift, id_restaurant);
*/