CREATE DATABASE `tfg_be_bbdd`;
USE `tfg_be_bbdd`;

-- 1. USERS
CREATE TABLE users ( 
    ID_USER INT auto_increment PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

-- 2. RESTAURANTS
CREATE TABLE restaurants (
    ID_RESTAURANT VARCHAR(255) PRIMARY KEY,
    ID_USER INT,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    COUNTRY VARCHAR(100),
    PHONE VARCHAR(20),
    CAPACITY INT,
    TOTAL_TABLES INT,
    
    FOREIGN KEY (ID_USER) REFERENCES users(ID_USER)
    ON DELETE CASCADE
);

-- 3. SHIFTS (MOVER AQUÍ)
CREATE TABLE shifts (
	ID_SHIFT INT auto_increment PRIMARY KEY,
    ASSIGN_SHIFT VARCHAR(255)
);

CREATE TABLE roles (
ID_ROLE INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(50)
);

-- 4. EMPLOYEES
CREATE TABLE employees (
	ID_USER INT PRIMARY KEY,
    ID_RESTAURANT VARCHAR(255) NULL,
    ID_SHIFT INT,
    ID_EMPLOYEE VARCHAR(255),
    ID_ROLE INT,
	#EMPLOYEE_TYPE ENUM('TEAM_LEADER','ASSISTANT_MANAGER','MANAGER','EMPLOYEE','OWNER') DEFAULT ('EMPLOYEE'),
    HOURLY_WAGE DOUBLE,
    HIRE_DATE DATE,
    
    FOREIGN KEY (ID_USER) REFERENCES users(ID_USER)
    ON DELETE CASCADE,
    FOREIGN KEY (ID_RESTAURANT) REFERENCES restaurants(ID_RESTAURANT)
    ON DELETE SET NULL,
    FOREIGN KEY (ID_SHIFT) REFERENCES shifts(ID_SHIFT),
    FOREIGN KEY (ID_ROLE) REFERENCES roles(ID_ROLE)
    
);



-- 5. ADMINS
CREATE TABLE admins (
	ID_ADMIN INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_NAME VARCHAR(50) DEFAULT 'ROLE_SUPERADMIN'
    );

-- 6. TABLES
CREATE TABLE tables (
    ID_TABLE INT AUTO_INCREMENT PRIMARY KEY,
    TABLE_NUMBER INT NOT NULL,
    TABLE_CAPACITY INT NOT NULL,
    STATUS ENUM('BOOKED','NOT_BOOKED','CONFIRMED','PENDING') NOT NULL, 
    ID_RESTAURANT VARCHAR(255) NOT NULL, 
    FOREIGN KEY (ID_RESTAURANT) REFERENCES restaurants(ID_RESTAURANT)
);

-- 7. TABLE_ASSIGNMENT
CREATE TABLE table_assignment (
    ID_ASSIGMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_TABLE INT NOT NULL,
    ID_EMPLOYEE INT NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    FOREIGN KEY (ID_TABLE) REFERENCES tables(ID_TABLE),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES employees(ID_USER)
);
