CREATE DATABASE `tfg_be_bbdd`;
USE `tfg_be_bbdd`;

CREATE TABLE USERS ( 
    ID_USER INT auto_increment PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
	CONTRACTED_DATE DATE,
    ACTIVE BOOLEAN,
    ROL ENUM('ADMIN','EMPLOYEE') NOT NULL,
    EMPLOYEE_TYPE VARCHAR(200)
);

CREATE TABLE RESTAURANTS (
    ID_RESTAURANT VARCHAR(255) PRIMARY KEY,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    COUNTRY VARCHAR(100),
    PHONE VARCHAR(20),
    CAPACITY INT,
    ID_MANAGER INT,
    FOREIGN KEY (ID_MANAGER) REFERENCES USERS(ID_USER)
);

CREATE TABLE TABLES (
    ID_TABLE INT AUTO_INCREMENT PRIMARY KEY,
    TABLE_NUMBER INT NOT NULL,
    CAPACITY INT NOT NULL,
    STATUS ENUM('BOOKED','NOT_BOOKED','CONFIRMED','PENDING') NOT NULL, 
    ID_RESTAURANT INT NOT NULL, 
    FOREIGN KEY (ID_RESTAURANT) REFERENCES RESTAURANTS(ID_RESTAURANT)
);